### ISSUE TITLE
[PE-D][Tester B] Adding team with hyphen in name is not allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#101]
According to the user guide, name can only be alphanumeric but the error message shows it can contain hyphens and underscores.
![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/60cd3e3b-831d-4697-8075-8cd7fca99ca3.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: ThomasHoooo/ped#8

**Comment by Eclipse-Dominator** [comment]
Name issues are addressed by #143
