### ISSUE TITLE
[PE-D][Tester A] App has no error message when add command pairs with invalid email format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#102]
![image.png](https://raw.githubusercontent.com/PokezardVGC/ped/main/files/11b0bd36-eddf-4d77-8116-c9fad4604cad.png)

No error message when inputing email address without @ command. It remains at the output of previous input

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: PokezardVGC/ped#8

**Comment by Eclipse-Dominator** [comment]
This issue will be addressed by #153
