### ISSUE TITLE
[PE-D][Tester E] `foreach` command does not seem to be supported

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#103]
## Description

When trying out the `foreach` command according to the user guide, I was unable to get it to execute. It seems that it not recognized as a proper subcommand.

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/e3f5cdd8-55de-4e0e-935e-dadba84f1548.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: shenyih0ng/ped#5

**Comment by Eclipse-Dominator** [comment]
foreach parser wasnt added to the AddressBookParser resulting in the command not being found. This issues has been addressed as of #143
