### ISSUE TITLE
[PE-D][Tester E] [`task select`] Misleading error message when a invalid task index is given

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#109]
## Description

The error message shown when a invalid task index is given to the `task select` command is a little misleading as it mentions that "person index" is invalid instead.

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/ee809256-8bbd-4b46-a3d5-cd5cd79b3fd7.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: shenyih0ng/ped#6

**Comment by Eclipse-Dominator** [comment]
Index related error messages updated as of #151
