### ISSUE TITLE
Add a skeletal Project Portfolio Page (PPP)

### ISSUE THREAD

**Issue by connlim** [AY2223S1-CS2103T-T11-1/tp#11]
Create a skeletal version of your Project Portfolio Page (PPP).

* Just the headings are enough. You can write to be added soon as placeholders for content.
* PDF conversion not required.
* File name (i.e., in the repo): `docs/team/github_username_in_lower_case.md` e.g., `docs/team/goodcoder123.md`

- [x] Eric
- [x] Zhaoqi
- [x] Connor
- [x] Jason
- [x] Safwan

**Comment by autumn-sonata** [comment]
All PPP have been added to `docs/team`.
