### ISSUE TITLE
[PE-D][Tester D] Inaccuracy in error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#110]
![image.png](https://raw.githubusercontent.com/nickeltea/ped/main/files/6eebd271-3eb7-44f0-be8f-9fb6bf4b174a.png)

The command to delete an invalid "team" index, but the error message informs that the "person" index is invalid.

The error message does not match the error.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: nickeltea/ped#6

**Comment by Eclipse-Dominator** [comment]
Exception messages standardized as of #151
