### ISSUE TITLE
[PE-D][Tester C] Tasks are not created with descriptions

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#117]
When adding new tasks, the description does not seem to be created together with the task.

For example, using command `task add t/Sample Task d/Description` results in `New task have been added: /namingIsHard/Sample Task`.

We can confirm that the description is not created by using command `task select 2 contains description`, which gives `result is false`.
![image.png](https://raw.githubusercontent.com/misterpuffin/ped/main/files/a799ce15-3414-4510-8d5d-c1d07fb6e6e0.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: misterpuffin/ped#6

**Comment by Eclipse-Dominator** [comment]
Previously, descriptions are designed to be viewed in a detailed view panel and hidden in list view which was scrapped as of v1.4. 
Description are not visible in the menu as of #143
