### ISSUE TITLE
[PE-D][Tester B] Foreach command for task not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#120]
I tried to mark each task as done but it shows that my command is invalid with the error message.
![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/69695487-7e76-4761-8d94-8053c36c00a6.png)

I tried to look up on user guide but there is no info either.

![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/2df10085-060c-40f8-aaf6-87bb263a8bd3.png)

I am unsure of what are the possible parameters to enter.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ThomasHoooo/ped#12

**Comment by Eclipse-Dominator** [comment]
task foreach command was not added to the Command Parser resulting in foreach commands related to task to not be detected by the user. This is fixed by #143
