### ISSUE TITLE
[PE-D][Tester A] Incorrect error message

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#121]
![image.png](https://raw.githubusercontent.com/PokezardVGC/ped/main/files/ff5d7f4a-a975-48fc-be6e-39be3020bd8f.png)

Wrong error message when trying to delete task with invalid index

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: PokezardVGC/ped#14

**Comment by Eclipse-Dominator** [comment]
Error message standardized as of #151
