### ISSUE TITLE
[PE-D][Tester D] Feature does not work as described in user guide.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#124]
![image.png](https://raw.githubusercontent.com/nickeltea/ped/main/files/9f8066b8-4863-488f-a508-2d9d3479cdc7.png)

![image.png](https://raw.githubusercontent.com/nickeltea/ped/main/files/373e5c36-9b2a-4fc9-8060-9bfe9ce153b2.png)

The feature is incomplete, as can be seen above. However, the product can still be used.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: nickeltea/ped#9

**Comment by Eclipse-Dominator** [comment]
This is a documentation bug. 

This correct syntax should be 
- `field add<t|g|u>/<index><type> <value>` 
- `<selected item> field add <type> <value>`

**Comment by Eclipse-Dominator** [comment]
Duplicate of #107
