### ISSUE TITLE
[PE-D][Tester E] [`task select`] Unsure of what commands are available

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#126]
## Description

It is not mentioned in the user guide what are the available commands for `task select`. Only managed to try out `isComplete` which is mentioned in the UG.

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/5aa5fe44-5e21-47af-a4a8-6b7b727d7ec5.png)

In the help message, it was mentioned that `contains` / `contains description` could be a possible command. However upon tasking, it returns "result is false" for supposedly valid commands

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/12e46d5e-7248-405d-b214-0a63b6de36d5.png)

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/ff14d6e9-5fa1-4a3f-8c1a-c4a68b62bc4a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: shenyih0ng/ped#8

**Comment by Eclipse-Dominator** [comment]
contains check if the selected item contains an attribute/field with the type of description.
Custom field can be added via 
- `<selected item> field add <type> <value> `
- field add `<g|u|t>/<index> <type> <value> `

**Comment by Eclipse-Dominator** [comment]
As of 1.4, we have enabled the display of attribute type by default for ease of visibility.
