### ISSUE TITLE
[PE-D][Tester B] Example and format for task progress doesn't match

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#128]
I am unsure whether there will be a prefix `i/` for index as the documents don't match

![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/56b92b02-03db-4ddb-acfe-9a6cede1c9b0.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: ThomasHoooo/ped#15

**Comment by Eclipse-Dominator** [comment]
This feature is not complete and will be removed in v1.4
