### ISSUE TITLE
[PE-D][Tester B] task progress feature is not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#131]
Followed the userguide exactly, but nothing has shown and the command seems invalid.

![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/f6cbe042-7b25-434e-95bf-735a5728cc37.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ThomasHoooo/ped#16

**Comment by Eclipse-Dominator** [comment]
The feature is incomplete and hence will be removed in version v1.4
