### ISSUE TITLE
[PE-D][Tester D] The user guide includes commands that cannot be tested

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#134]
![image.png](https://raw.githubusercontent.com/nickeltea/ped/main/files/cb612c9f-dc73-47e6-a676-4397ef0d4f6f.png)

Since the `addfield` command has not been implemented/cannot be used, it is not possible to test the `editfield` and `rmfield` commands.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nickeltea/ped#11

**Comment by Eclipse-Dominator** [comment]
This is a documentation bug. 

This correct syntax should be 
- `field add <t|g|u>/<index><type> <value>` 
- `<selected item> field add <type> <value>`

and relevant command edit and delete functions similarly as above.

**Comment by Eclipse-Dominator** [comment]
Duplicate of #107
