### ISSUE TITLE
[PE-D][Tester E] [`person new`] Unexpected behavior with erroneous command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#136]
## Description

A user might expect this to be a invalid command format error.

![image.png](https://raw.githubusercontent.com/shenyih0ng/ped/main/files/46d42dbf-ca4a-48fc-beec-c6306b1ce77d.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: shenyih0ng/ped#9

**Comment by connlim** [comment]
This is fixable but is it really worth the effort? This is user error. It is technically a valid command according to our syntax.
