### ISSUE TITLE
[PE-D][Tester B] Exit command will cause java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#75]
![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/47433220-50dc-44eb-8403-c82b35d30d39.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ThomasHoooo/ped#1

**Comment by Eclipse-Dominator** [comment]
Duplicate issue
This issue is a result of the jar file having insufficient permission to save data to a write-protected directory and not due to task select being not functional. This is the same as #75

**Comment by autumn-sonata** [comment]
Explanation is given in the `FAQ` section of the user guide.
