### ISSUE TITLE
[PE-D][Tester C] Sequence Command in UG lacks documentation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#86]
Small issue but I think the sequence command in UG should be updated! There doesn't seem to be instructions on how to use this command.

https://ay2223s1-cs2103t-t11-1.github.io/tp/UserGuide.html#sequence-command-seq

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: misterpuffin/ped#2

**Comment by Eclipse-Dominator** [comment]
Added to UG as of #146
