### ISSUE TITLE
Project Website: About Us

### ISSUE THREAD

**Issue by connlim** [AY2223S1-CS2103T-T11-1/tp#9]
This page (in the /docs folder) is used for module admin purposes. Please follow the format closely or else our scripts will not be able to give credit for your work.

* Add your own details. Include a suitable photo as described here.
* There is no need to mention the the tutor/lecturer, but OK to do so too.
* The filename of the profile photo should be `docs/images/github_username_in_lower_case.png`
   Note the need for lower case (why lowercase?) e.g. JohnDoe123 -> `docs/images/johndoe123.png not docs/images/JohnDoe123.png`.
   If your photo is in jpg format, name the file as .png anyway.
* Indicate the different roles played and responsibilities held by each team member. You can reassign these roles and responsibilities (as explained in Admin Project Scope) later in the project, if necessary.

- [x] Eric
- [x] Zhaoqi
- [x] Connor
- [x] Jason
- [x] Safwan

**Comment by autumn-sonata** [comment]
All images and role indication in `AboutUs.md` have been completed.
