### ISSUE TITLE
[PE-D][Tester A] Unsure of how to use seq command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#93]
![image.png](https://raw.githubusercontent.com/PokezardVGC/ped/main/files/ab445f67-32fb-4f8c-989d-bb62eaace694.png)

No UG for seq command, actually lost on how to use

-------------
Labels: `severity.High` `type.DocumentationBug`
original: PokezardVGC/ped#6

**Comment by Eclipse-Dominator** [comment]
Duplicate of #86
