### ISSUE TITLE
[PE-D][Tester D] Duplicate persons not detected accurately

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T11-1/tp#98]
![image.png](https://raw.githubusercontent.com/nickeltea/ped/main/files/6b917607-ae3a-4186-a184-2f74419c9e15.png)

"John Doe", "John doe" and "John  doe" are likely to be the same people, but these duplicates were not detected by the product though exact name matches were detected. Thus, the feature does not work as expected.

It may be good for the product to give a warning in such near match cases so that the user can make the final decision.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nickeltea/ped#4

**Comment by jasonchristopher21** [comment]
Thanks for the report. However, this feature will not be fixed as of v1.4 due to feature freeze.
