### ISSUE TITLE
[PE-D][Tester B] Adding team with underscore is not allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#99]
![image.png](https://raw.githubusercontent.com/ThomasHoooo/ped/main/files/b2c75861-6323-4a1e-ba3d-a746494b873d.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ThomasHoooo/ped#7

**Comment by Eclipse-Dominator** [comment]
Naming issues addressed as of #143
